### ISSUE TITLE
Is it possible to access a hover event on summarized edges? 

### ISSUE THREAD

**Issue by markus-ebner** [dash14/v-network-graph#11]
Hi @dash14, 

I'm working with the summarized edges feature at the moment. I got two questions for you :) 

- I try to get the event `edge:pointerover` but it did not work. Is it possible to have a hover event on summarized edges? 
- Additionally, is it possible to add a custom label to a summerized edge that can be added at a specific `NodeLabelDirection`? 

Thanks for your amazing stuff 🥇

**Comment by dash14** [comment]
Hi @markus-ebner,
Thank you very much for using the v-network-graph. Such feedbacks motivate me.

Thanks for your question about summarized edges.
The summarized edge remained a low priority because there was no UI to select only some of the multiple edges that were summarized, and it was hard to implement.
As a rush job, I implemented the following ([v0.3.3](https://github.com/dash14/v-network-graph/releases/tag/v0.3.3)):
* Fire events of summarized edges
  * `edge:pointerover`, `edge:pointerout`
  * `edge:click`
  * `edge:select` (only if `configs.edge.selectable` is set to true)
* Slot for draw labels of summarized edges

### Fire events of summarized edges
I have implemented firing events, but I have not implemented changing the appearance by mouse operation.
I added a class to the element in case you want to change the appearance such as the color of the line by selecting or hovering the summarized edge.
In the future, I may implement changing the appearance, but for the time being, please specify the style as follows.
```css
.v-network-graph .v-line-summarized > path {
  cursor: pointer; 
  transition: stroke-width 0.1s linear;
}
.v-network-graph .v-line-summarized.hovered > path {
  stroke: red;
  stroke-width: 8px;
  vector-effect: non-scaling-stroke;
}
.v-network-graph .v-line-summarized.selected > path {
  stroke: green;
  stroke-width: 8px;
  vector-effect: non-scaling-stroke;
}
```

### Slot for draw labels for summarized edges
Please see the sample below.
https://dash14.github.io/v-network-graph/examples/labels.html#summarized-edge-labels
